spring.application.name=demo

# (Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#  Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
